storage_root: <%= File.join(Rails.root, 'tmp', 'development_storage') %>
manifests_root: <%= File.join(Rails.root, 'tmp', 'development_manifests') %>
#Note that this is not a hard limit: a single file archive can be any size and
#a multi-file one can double this
archive_size_limit: <%= 100.megabytes %>