#NOTE: You'll probably want to set much of this in ./production.local.yml and have capistrano link that in
#path to main storage
storage_path: /path/to/main/storage
#path the directory where manifests will be passed back and forth with glacier-fs
manifests_path: /path/to/manifest/storage
#Note that this is not a hard limit: a single file archive can be any size and
#a multi-file one can double this, so set to about half the desired maximum
archive_size_limit: <%= 100.gigabytes %>
amqp:
  outgoing_queue: amazon_web_to_fs
  incoming_queue: amazon_fs_to_web
  connection:
    host: localhost
email:
  admin: admin@example.com
  no_reply: no-reply@example.com
smtp:
  smtp_settings:
    address: express-smtp.cites.uiuc.edu
    domain: my.server-domain
  web_host: "my.web.host"